#!/bin/bash
# Setup passwordless sudo for daemira binary
# This allows running daemira with sudo without entering a password

set -e

USERNAME="${1:-$(whoami)}"
DAEMIRA_PATH="${2:-/usr/local/bin/daemira}"

echo "Setting up passwordless sudo for daemira..."
echo "Username: $USERNAME"
echo "Daemira path: $DAEMIRA_PATH"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "This script must be run as root (use sudo)"
    exit 1
fi

# Check if daemira binary exists
if [ ! -f "$DAEMIRA_PATH" ]; then
    echo "Warning: daemira binary not found at $DAEMIRA_PATH"
    echo "You can specify the path as the second argument:"
    echo "  sudo ./scripts/setup-sudo-daemira.sh $USERNAME /path/to/daemira"
    echo ""
    echo "For development (running from source):"
    echo "  sudo ./scripts/setup-sudo-daemira.sh $USERNAME \"go run *\""
    echo ""
    read -p "Continue anyway? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Backup sudoers file
SUDOERS_FILE="/etc/sudoers.d/daemira-$USERNAME"
if [ -f "$SUDOERS_FILE" ]; then
    echo "Backing up existing sudoers file..."
    cp "$SUDOERS_FILE" "${SUDOERS_FILE}.bak.$(date +%s)"
fi

# Create sudoers entry
echo "Creating sudoers entry..."
cat > "$SUDOERS_FILE" <<EOF
# Passwordless sudo for daemira
# Generated by setup-sudo-daemira.sh on $(date)
$USERNAME ALL=(ALL) NOPASSWD: $DAEMIRA_PATH
EOF

# Validate sudoers file
if visudo -c -f "$SUDOERS_FILE" 2>/dev/null; then
    echo "✓ Sudoers entry created successfully!"
    echo ""
    echo "You can now run daemira with sudo without a password:"
    echo "  sudo $DAEMIRA_PATH"
    echo ""
    echo "Or for development:"
    echo "  sudo go run main.go"
else
    echo "✗ Error: Invalid sudoers syntax. Restoring backup..."
    if [ -f "${SUDOERS_FILE}.bak" ]; then
        mv "${SUDOERS_FILE}.bak" "$SUDOERS_FILE"
    else
        rm -f "$SUDOERS_FILE"
    fi
    exit 1
fi

